# Generated by Django 4.2.2 on 2023-06-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=25)),
                (
                    "modified_date",
                    models.DateTimeField(verbose_name="last modified date"),
                ),
            ],
        ),
    ]
